"""Trade model — individual trade records from backtests and live deployments."""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from uuid import UUID, uuid4

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Numeric,
    String,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from msai.models.base import Base


class Trade(Base):
    """A single trade execution record.

    Trades are generated by either a backtest or a live deployment — never
    both.  The CHECK constraint ``ck_trade_source`` enforces that exactly
    one of ``backtest_id`` or ``deployment_id`` is set.

    The ``strategy_code_hash`` is denormalized here intentionally so that
    trades can be attributed to an exact strategy version even if the parent
    backtest/deployment is deleted.
    """

    __tablename__ = "trades"
    __table_args__ = (
        CheckConstraint(
            "(backtest_id IS NOT NULL AND deployment_id IS NULL) "
            "OR (backtest_id IS NULL AND deployment_id IS NOT NULL)",
            name="ck_trade_source",
        ),
        Index("ix_trades_backtest_id", "backtest_id"),
        Index("ix_trades_deployment_id", "deployment_id"),
        Index("ix_trades_strategy_id", "strategy_id"),
        Index("ix_trades_executed_at", "executed_at"),
        Index("ix_trades_instrument", "instrument"),
        # Partial unique index on (deployment_id, broker_trade_id) so a
        # reconciliation-time fill replay (nautilus.md gotcha 19 — IB
        # reports historical fills on engine restart) can't create a
        # duplicate Trade row. Partial because backtest rows have no
        # broker-side id and would otherwise collide on NULL.
        Index(
            "ix_trades_broker_trade_id_deployment",
            "deployment_id",
            "broker_trade_id",
            unique=True,
            postgresql_where="broker_trade_id IS NOT NULL",
        ),
    )

    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)
    backtest_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("backtests.id"), nullable=True
    )
    deployment_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("live_deployments.id"), nullable=True
    )
    strategy_id: Mapped[UUID] = mapped_column(
        ForeignKey("strategies.id"), nullable=False
    )
    strategy_code_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    instrument: Mapped[str] = mapped_column(String(100), nullable=False)
    side: Mapped[str] = mapped_column(String(10), nullable=False)
    quantity: Mapped[Decimal] = mapped_column(Numeric(18, 8), nullable=False)
    price: Mapped[Decimal] = mapped_column(Numeric(18, 8), nullable=False)
    commission: Mapped[Decimal | None] = mapped_column(Numeric(18, 8), nullable=True)
    broker_trade_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    pnl: Mapped[Decimal | None] = mapped_column(Numeric(18, 8), nullable=True)
    is_live: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")
    executed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())

    # Relationships
    backtest: Mapped["Backtest | None"] = relationship(lazy="selectin")  # noqa: F821
    deployment: Mapped["LiveDeployment | None"] = relationship(lazy="selectin")  # noqa: F821
    strategy: Mapped["Strategy"] = relationship(lazy="selectin")  # noqa: F821
