"""create all tables

Revision ID: 022772d92139
Revises: 
Create Date: 2026-02-25 20:11:36.507447

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '022772d92139'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entra_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), server_default='viewer', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('entra_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('strategy_class', sa.String(length=255), nullable=False),
    sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_created_by'), 'strategies', ['created_by'], unique=False)
    op.create_table('backtests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_code_hash', sa.String(length=64), nullable=False),
    sa.Column('strategy_git_sha', sa.String(length=40), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('instruments', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('progress', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_path', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtests_created_by'), 'backtests', ['created_by'], unique=False)
    op.create_index(op.f('ix_backtests_strategy_id'), 'backtests', ['strategy_id'], unique=False)
    op.create_table('live_deployments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_code_hash', sa.String(length=64), nullable=False),
    sa.Column('strategy_git_sha', sa.String(length=40), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('instruments', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='stopped', nullable=False),
    sa.Column('paper_trading', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_deployments_started_by'), 'live_deployments', ['started_by'], unique=False)
    op.create_index(op.f('ix_live_deployments_strategy_id'), 'live_deployments', ['strategy_id'], unique=False)
    op.create_table('strategy_daily_pnl',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('deployment_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cumulative_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('capital_used', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('num_trades', sa.Integer(), server_default='0', nullable=False),
    sa.Column('win_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('loss_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['live_deployments.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'deployment_id', 'date', name='uq_strategy_deployment_date')
    )
    op.create_index('ix_strategy_daily_pnl_strategy_date', 'strategy_daily_pnl', ['strategy_id', 'date'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('backtest_id', sa.Uuid(), nullable=True),
    sa.Column('deployment_id', sa.Uuid(), nullable=True),
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_code_hash', sa.String(length=64), nullable=False),
    sa.Column('instrument', sa.String(length=100), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('is_live', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(backtest_id IS NOT NULL AND deployment_id IS NULL) OR (backtest_id IS NULL AND deployment_id IS NOT NULL)', name='ck_trade_source'),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['live_deployments.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_backtest_id', 'trades', ['backtest_id'], unique=False)
    op.create_index('ix_trades_deployment_id', 'trades', ['deployment_id'], unique=False)
    op.create_index('ix_trades_executed_at', 'trades', ['executed_at'], unique=False)
    op.create_index('ix_trades_instrument', 'trades', ['instrument'], unique=False)
    op.create_index('ix_trades_strategy_id', 'trades', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_strategy_id', table_name='trades')
    op.drop_index('ix_trades_instrument', table_name='trades')
    op.drop_index('ix_trades_executed_at', table_name='trades')
    op.drop_index('ix_trades_deployment_id', table_name='trades')
    op.drop_index('ix_trades_backtest_id', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_strategy_daily_pnl_strategy_date', table_name='strategy_daily_pnl')
    op.drop_table('strategy_daily_pnl')
    op.drop_index(op.f('ix_live_deployments_strategy_id'), table_name='live_deployments')
    op.drop_index(op.f('ix_live_deployments_started_by'), table_name='live_deployments')
    op.drop_table('live_deployments')
    op.drop_index(op.f('ix_backtests_strategy_id'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_created_by'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_index(op.f('ix_strategies_created_by'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    # ### end Alembic commands ###
