"""Order audit hook — persist every order intent with ``client_order_id``.

Phase 1 task 1.11 (Codex finding #7 — ``client_order_id`` is the
stable correlation key). Every order the platform attempts gets a
row in ``order_attempt_audits``:

1. On submission → ``status='submitted'`` row INSERT with
   ``client_order_id`` as the correlation key
2. On accepted / filled / rejected / cancelled / denied → UPDATE the
   existing row by ``client_order_id``

The ``client_order_id`` is generated by Nautilus at order-submit time
(``order.client_order_id.value``) and is unique across the lifetime
of the venue's order-id tag. Task 1.10 pins the ``order_id_tag`` to
the ``deployment_slug``, which makes the ``client_order_id`` prefix
stable across restarts — the audit hook can therefore correlate
orders to a specific deployment without any extra bookkeeping.

Architecture
------------

The writer (this module) is a pure async class with no Nautilus
imports. It takes an ``async_sessionmaker`` and the per-deployment
context (deployment_id or backtest_id, strategy_id, code hash, etc.)
at construction time.

The Strategy mixin that WIRES this writer into Nautilus
(``on_order_accepted`` / ``on_order_filled`` / ``on_order_denied``
hooks) lands in Task 4.4 alongside the first real strategy-level
integration test. This split keeps the writer fully unit-testable
without touching Nautilus or IB Gateway — Task 4.4 just wires the
real events through.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import UTC, datetime
from decimal import Decimal  # noqa: TC003 — used in dataclass default type
from typing import TYPE_CHECKING
from uuid import UUID, uuid4  # noqa: TC003 — used in dataclass field types

from sqlalchemy import select, update

from msai.models import OrderAttemptAudit

if TYPE_CHECKING:
    from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker


log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Status state machine (mirrors the OrderAttemptAudit model docstring)
# ---------------------------------------------------------------------------

_ORDER_STATUS_SUBMITTED = "submitted"
_ORDER_STATUS_ACCEPTED = "accepted"
_ORDER_STATUS_FILLED = "filled"
_ORDER_STATUS_PARTIALLY_FILLED = "partially_filled"
_ORDER_STATUS_CANCELLED = "cancelled"
_ORDER_STATUS_REJECTED = "rejected"
_ORDER_STATUS_DENIED = "denied"


@dataclass(frozen=True)
class OrderSubmittedFacts:
    """Everything the writer needs to INSERT a 'submitted' row.

    Held as a frozen dataclass so the caller (Strategy mixin) can
    construct one at order-submit time from the ``Order`` object and
    the per-deployment context, then hand it to
    :meth:`OrderAuditWriter.write_submitted` in a single call.
    """

    client_order_id: str
    strategy_id: UUID
    strategy_code_hash: str
    instrument_id: str
    side: str
    quantity: Decimal
    price: Decimal | None
    order_type: str
    ts_attempted: datetime
    # Exactly one of these must be populated — the CHECK constraint
    # on the table enforces it at the DB layer (v5 iter2 P2 fix).
    deployment_id: UUID | None = None
    backtest_id: UUID | None = None
    is_live: bool = True
    strategy_git_sha: str | None = None


class OrderAuditWriter:
    """Persists order lifecycle events to ``order_attempt_audits``.

    Instances are per-deployment (or per-backtest). The caller
    passes the long-lived per-run context (``deployment_id``,
    ``strategy_id``, ``strategy_code_hash``) so every write only has
    to carry the order-specific fields.
    """

    def __init__(
        self,
        *,
        db: async_sessionmaker[AsyncSession],
    ) -> None:
        self._db = db

    # ------------------------------------------------------------------
    # Writers
    # ------------------------------------------------------------------

    async def write_submitted(self, facts: OrderSubmittedFacts) -> UUID:
        """INSERT a new ``submitted`` audit row.

        Returns the new row's primary key. The correlation key for
        every subsequent UPDATE is ``facts.client_order_id`` — the
        primary key is returned mostly for logging.

        Raises:
            ValueError: If neither ``deployment_id`` nor
                ``backtest_id`` is populated. The DB CHECK constraint
                would catch it anyway, but an early application-level
                check lets us surface the problem with the exact
                ``client_order_id`` context.
        """
        if (facts.deployment_id is None) == (facts.backtest_id is None):
            # Both NULL or both set. XOR violation.
            raise ValueError(
                "OrderSubmittedFacts must set exactly one of "
                "deployment_id / backtest_id (the XOR CHECK constraint "
                "on order_attempt_audits rejects any other shape). "
                f"client_order_id={facts.client_order_id}"
            )

        row_id = uuid4()
        async with self._db() as session, session.begin():
            audit = OrderAttemptAudit(
                id=row_id,
                client_order_id=facts.client_order_id,
                deployment_id=facts.deployment_id,
                backtest_id=facts.backtest_id,
                strategy_id=facts.strategy_id,
                strategy_code_hash=facts.strategy_code_hash,
                strategy_git_sha=facts.strategy_git_sha,
                instrument_id=facts.instrument_id,
                side=facts.side,
                quantity=facts.quantity,
                price=facts.price,
                order_type=facts.order_type,
                ts_attempted=facts.ts_attempted,
                status=_ORDER_STATUS_SUBMITTED,
                is_live=facts.is_live,
            )
            session.add(audit)
        from msai.services.observability.trading_metrics import ORDERS_SUBMITTED
        ORDERS_SUBMITTED.inc()
        log.info(
            "order_audit_submitted",
            extra={
                "client_order_id": facts.client_order_id,
                "deployment_id": str(facts.deployment_id) if facts.deployment_id else None,
                "backtest_id": str(facts.backtest_id) if facts.backtest_id else None,
                "instrument_id": facts.instrument_id,
            },
        )
        return row_id

    async def update_accepted(self, client_order_id: str, *, broker_order_id: str | None) -> None:
        """Broker acknowledged the order. Record the broker-side id so
        restart-time reconciliation (Task 4.1) can correlate fills
        back to this row."""
        await self._update_status(
            client_order_id,
            status=_ORDER_STATUS_ACCEPTED,
            broker_order_id=broker_order_id,
        )

    async def update_filled(self, client_order_id: str) -> None:
        """Order fully filled. Terminal state."""
        await self._update_status(client_order_id, status=_ORDER_STATUS_FILLED)
        from msai.services.observability.trading_metrics import ORDERS_FILLED
        ORDERS_FILLED.inc()

    async def update_partially_filled(self, client_order_id: str) -> None:
        """Order partially filled — not yet terminal, further fills
        may follow and will flip it to ``filled``."""
        await self._update_status(client_order_id, status=_ORDER_STATUS_PARTIALLY_FILLED)

    async def update_cancelled(self, client_order_id: str, *, reason: str | None = None) -> None:
        """Order cancelled (by the caller or by broker timeout)."""
        await self._update_status(client_order_id, status=_ORDER_STATUS_CANCELLED, reason=reason)

    async def update_rejected(self, client_order_id: str, *, reason: str | None) -> None:
        """Broker rejected the order. The ``reason`` is typically the
        broker's error message (e.g. 'Insufficient buying power')."""
        await self._update_status(client_order_id, status=_ORDER_STATUS_REJECTED, reason=reason)

    async def update_denied(self, client_order_id: str, *, reason: str | None) -> None:
        """Risk engine denied the order before submission. The row
        still carries ``deployment_id`` but ``broker_order_id`` stays
        NULL forever because the order never reached the broker.
        """
        await self._update_status(client_order_id, status=_ORDER_STATUS_DENIED, reason=reason)

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    async def _update_status(
        self,
        client_order_id: str,
        *,
        status: str,
        broker_order_id: str | None = None,
        reason: str | None = None,
    ) -> None:
        """Apply one status transition to the row keyed by
        ``client_order_id``.

        Only mutates columns the caller provided — NULL in any
        keyword-only argument means "leave this column as-is". That
        way ``update_filled`` doesn't clobber the ``broker_order_id``
        that ``update_accepted`` wrote earlier in the lifecycle.
        """
        values: dict[str, object] = {"status": status}
        if broker_order_id is not None:
            values["broker_order_id"] = broker_order_id
        if reason is not None:
            values["reason"] = reason

        async with self._db() as session, session.begin():
            result = await session.execute(
                update(OrderAttemptAudit)
                .where(OrderAttemptAudit.client_order_id == client_order_id)
                .values(**values)
                .returning(OrderAttemptAudit.id)
            )
            row_id = result.scalar_one_or_none()

        if row_id is None:
            # No row to update — log loudly but don't raise. The
            # caller (Strategy event handler) can't do anything
            # meaningful with an exception here, and the audit is a
            # best-effort recording path.
            log.error(
                "order_audit_update_missing_row",
                extra={
                    "client_order_id": client_order_id,
                    "status": status,
                },
            )
            return

        log.info(
            "order_audit_status_updated",
            extra={
                "client_order_id": client_order_id,
                "status": status,
                "broker_order_id": broker_order_id,
            },
        )


async def lookup_by_client_order_id(
    db: async_sessionmaker[AsyncSession], client_order_id: str
) -> OrderAttemptAudit | None:
    """Read-only helper: fetch an audit row by its correlation key.

    Used by tests and by operator debug tooling. Returns ``None`` if
    no row is found rather than raising so callers can distinguish
    "never written" from "deleted".
    """
    async with db() as session:
        result = await session.execute(
            select(OrderAttemptAudit).where(OrderAttemptAudit.client_order_id == client_order_id)
        )
        return result.scalar_one_or_none()


def utc_now() -> datetime:
    """Stable ``datetime.now(UTC)`` callable for test monkey-patching."""
    return datetime.now(UTC)
