"""Order audit hook — persist every order intent with ``client_order_id``.

Phase 1 task 1.11 (Codex finding #7 — ``client_order_id`` is the
stable correlation key). Every order the platform attempts gets a
row in ``order_attempt_audits``:

1. On submission → ``status='submitted'`` row INSERT with
   ``client_order_id`` as the correlation key
2. On accepted / filled / rejected / cancelled / denied → UPDATE the
   existing row by ``client_order_id``

The ``client_order_id`` is generated by Nautilus at order-submit time
(``order.client_order_id.value``) and is unique across the lifetime
of the venue's order-id tag. Task 1.10 pins the ``order_id_tag`` to
the ``deployment_slug``, which makes the ``client_order_id`` prefix
stable across restarts — the audit hook can therefore correlate
orders to a specific deployment without any extra bookkeeping.

Architecture
------------

The writer (this module) is a pure async class with no Nautilus
imports. It takes an ``async_sessionmaker`` and the per-deployment
context (deployment_id or backtest_id, strategy_id, code hash, etc.)
at construction time.

The Strategy mixin that WIRES this writer into Nautilus
(``on_order_accepted`` / ``on_order_filled`` / ``on_order_denied``
hooks) lands in Task 4.4 alongside the first real strategy-level
integration test. This split keeps the writer fully unit-testable
without touching Nautilus or IB Gateway — Task 4.4 just wires the
real events through.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import UTC, datetime
from decimal import Decimal  # noqa: TC003 — used in dataclass default type
from typing import TYPE_CHECKING
from uuid import UUID, uuid4  # noqa: TC003 — used in dataclass field types

from sqlalchemy import select, update
from sqlalchemy.dialects.postgresql import insert as pg_insert

from msai.models import OrderAttemptAudit, Trade

if TYPE_CHECKING:
    from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker


log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Status state machine (mirrors the OrderAttemptAudit model docstring)
# ---------------------------------------------------------------------------

_ORDER_STATUS_SUBMITTED = "submitted"
_ORDER_STATUS_ACCEPTED = "accepted"
_ORDER_STATUS_FILLED = "filled"
_ORDER_STATUS_PARTIALLY_FILLED = "partially_filled"
_ORDER_STATUS_CANCELLED = "cancelled"
_ORDER_STATUS_REJECTED = "rejected"
_ORDER_STATUS_DENIED = "denied"


@dataclass(frozen=True)
class TradeFillFacts:
    """One ``OrderFilled`` event, ready to INSERT into ``trades``.

    Phase 2 #4 port: the drill on 2026-04-15 confirmed that the
    existing ``order_attempt_audits`` table captures lifecycle state
    but the ``trades`` table — which the tax/regulatory audit and
    PnL aggregation depend on — was never populated from live fills.
    Every ``OrderFilled`` event from Nautilus's msgbus now flows
    through :meth:`OrderAuditWriter.write_trade_fill` to close that
    gap without touching the existing audit path.

    Nautilus assigns a unique ``trade_id`` per fill so this row can
    be deduped on ``(deployment_id, broker_trade_id)`` — the
    reconciliation-time replay on restart (nautilus.md gotcha 19)
    would otherwise double-count every historical fill.
    """

    broker_trade_id: str
    client_order_id: str
    deployment_id: UUID
    strategy_id: UUID
    strategy_code_hash: str
    instrument: str
    side: str
    quantity: Decimal
    price: Decimal
    commission: Decimal | None
    executed_at: datetime


@dataclass(frozen=True)
class OrderSubmittedFacts:
    """Everything the writer needs to INSERT a 'submitted' row.

    Held as a frozen dataclass so the caller (Strategy mixin) can
    construct one at order-submit time from the ``Order`` object and
    the per-deployment context, then hand it to
    :meth:`OrderAuditWriter.write_submitted` in a single call.
    """

    client_order_id: str
    strategy_id: UUID
    strategy_code_hash: str
    instrument_id: str
    side: str
    quantity: Decimal
    price: Decimal | None
    order_type: str
    ts_attempted: datetime
    # Exactly one of these must be populated — the CHECK constraint
    # on the table enforces it at the DB layer (v5 iter2 P2 fix).
    deployment_id: UUID | None = None
    backtest_id: UUID | None = None
    is_live: bool = True
    strategy_git_sha: str | None = None


@dataclass(frozen=True)
class OrderDeniedFacts:
    """Everything the writer needs to durably record a node-side
    halt/risk DENIAL — the complete order context for an order that
    was BLOCKED before submission.

    PR 2 T2 audit-completeness fix
    ------------------------------
    The node-side live halt gate (``RiskAwareStrategy``) blocks an
    opening order BEFORE it reaches Nautilus, so NO ``OrderSubmitted``
    event ever fires on the engine msgbus — the engine-level audit
    hook never inserts a ``submitted`` row. A bare
    :meth:`OrderAuditWriter.update_denied` (UPDATE-only on
    ``client_order_id``) therefore matches nothing and the denial is
    lost beyond a structured log line. ``nautilus.md`` #10 requires
    every order attempt on the real-money path to be durably
    auditable, so a halt-block must leave a ``denied`` row.

    :meth:`OrderAuditWriter.write_denied` UPSERTs on
    ``client_order_id`` so it records the denial whether or not a
    ``submitted`` row already exists (a denial AFTER a real
    submission still flips that row to ``denied`` rather than
    duplicating it). The frozen-dataclass shape mirrors
    :class:`OrderSubmittedFacts` so the caller (the strategy mixin)
    builds it from the per-run context + the blocked ``Order``.
    """

    client_order_id: str
    strategy_id: UUID
    strategy_code_hash: str
    instrument_id: str
    side: str
    quantity: Decimal
    price: Decimal | None
    order_type: str
    ts_attempted: datetime
    reason: str
    # Exactly one of these must be populated — the CHECK constraint
    # on the table enforces it at the DB layer. Node-side halt
    # denials are always live, so ``deployment_id`` is populated and
    # ``backtest_id`` stays ``None``.
    deployment_id: UUID | None = None
    backtest_id: UUID | None = None
    is_live: bool = True
    strategy_git_sha: str | None = None


class OrderAuditWriter:
    """Persists order lifecycle events to ``order_attempt_audits``.

    Instances are per-deployment (or per-backtest). The caller
    passes the long-lived per-run context (``deployment_id``,
    ``strategy_id``, ``strategy_code_hash``) so every write only has
    to carry the order-specific fields.
    """

    def __init__(
        self,
        *,
        db: async_sessionmaker[AsyncSession],
    ) -> None:
        self._db = db

    # ------------------------------------------------------------------
    # Writers
    # ------------------------------------------------------------------

    async def write_submitted(self, facts: OrderSubmittedFacts) -> UUID:
        """INSERT a new ``submitted`` audit row.

        Returns the new row's primary key. The correlation key for
        every subsequent UPDATE is ``facts.client_order_id`` — the
        primary key is returned mostly for logging.

        Raises:
            ValueError: If neither ``deployment_id`` nor
                ``backtest_id`` is populated. The DB CHECK constraint
                would catch it anyway, but an early application-level
                check lets us surface the problem with the exact
                ``client_order_id`` context.
        """
        if (facts.deployment_id is None) == (facts.backtest_id is None):
            # Both NULL or both set. XOR violation.
            raise ValueError(
                "OrderSubmittedFacts must set exactly one of "
                "deployment_id / backtest_id (the XOR CHECK constraint "
                "on order_attempt_audits rejects any other shape). "
                f"client_order_id={facts.client_order_id}"
            )

        row_id = uuid4()
        async with self._db() as session, session.begin():
            audit = OrderAttemptAudit(
                id=row_id,
                client_order_id=facts.client_order_id,
                deployment_id=facts.deployment_id,
                backtest_id=facts.backtest_id,
                strategy_id=facts.strategy_id,
                strategy_code_hash=facts.strategy_code_hash,
                strategy_git_sha=facts.strategy_git_sha,
                instrument_id=facts.instrument_id,
                side=facts.side,
                quantity=facts.quantity,
                price=facts.price,
                order_type=facts.order_type,
                ts_attempted=facts.ts_attempted,
                status=_ORDER_STATUS_SUBMITTED,
                is_live=facts.is_live,
            )
            session.add(audit)
        from msai.services.observability.trading_metrics import ORDERS_SUBMITTED

        ORDERS_SUBMITTED.inc()
        log.info(
            "order_audit_submitted",
            extra={
                "client_order_id": facts.client_order_id,
                "deployment_id": str(facts.deployment_id) if facts.deployment_id else None,
                "backtest_id": str(facts.backtest_id) if facts.backtest_id else None,
                "instrument_id": facts.instrument_id,
            },
        )
        return row_id

    async def update_accepted(self, client_order_id: str, *, broker_order_id: str | None) -> None:
        """Broker acknowledged the order. Record the broker-side id so
        restart-time reconciliation (Task 4.1) can correlate fills
        back to this row."""
        await self._update_status(
            client_order_id,
            status=_ORDER_STATUS_ACCEPTED,
            broker_order_id=broker_order_id,
        )

    async def update_filled(self, client_order_id: str) -> bool:
        """Order fully filled. Terminal state.

        Returns ``True`` when an existing audit row was flipped to
        ``filled``; ``False`` when no matching row existed. A
        ``False`` return means the caller saw an ``OrderFilled``
        before the corresponding ``OrderSubmitted`` insert committed
        (asyncio race between two ``create_task`` handlers) OR a
        reconciliation-time replay arrived for a fill whose original
        submit row was never persisted. The caller is responsible
        for deciding how to close that audit gap (Codex review P1).

        ``ORDERS_FILLED`` is NOT incremented here; the caller moves
        it to fire only on a genuinely new fill (after
        ``write_trade_fill`` returned ``True``) so a reconciliation
        replay doesn't inflate the metric.
        """
        return await self._update_status(client_order_id, status=_ORDER_STATUS_FILLED)

    async def write_trade_fill(self, facts: TradeFillFacts) -> bool:
        """INSERT a ``Trade`` row for one live fill, deduped by
        ``(deployment_id, broker_trade_id)``.

        Returns ``True`` when a new row was inserted, ``False`` when
        the partial unique index caught a duplicate (reconciliation
        replay — nautilus.md gotcha 19 — or a retried msgbus event).
        Uses ``INSERT ... ON CONFLICT DO NOTHING`` so dedup is atomic
        at the DB layer; callers don't need to hold a client-side
        cache to suppress replays.

        Caller invariant: the Nautilus msgbus handler bridges to this
        coroutine via ``loop.create_task`` so the DB write never
        blocks the trading thread (Scalability Hawk P0 — the
        Nautilus event loop must stay free for fill handlers even
        when Postgres is slow).
        """
        stmt = (
            pg_insert(Trade)
            .values(
                deployment_id=facts.deployment_id,
                strategy_id=facts.strategy_id,
                strategy_code_hash=facts.strategy_code_hash,
                instrument=facts.instrument,
                side=facts.side,
                quantity=facts.quantity,
                price=facts.price,
                commission=facts.commission,
                broker_trade_id=facts.broker_trade_id,
                client_order_id=facts.client_order_id,
                is_live=True,
                executed_at=facts.executed_at,
            )
            # ``index_where`` must match the partial-index predicate
            # on ``ix_trades_broker_trade_id_deployment`` exactly, or
            # Postgres raises "no unique or exclusion constraint
            # matching the ON CONFLICT specification".
            .on_conflict_do_nothing(
                index_elements=["deployment_id", "broker_trade_id"],
                index_where=Trade.broker_trade_id.isnot(None),
            )
            .returning(Trade.id)
        )
        async with self._db() as session, session.begin():
            result = await session.execute(stmt)
            inserted_id = result.scalar_one_or_none()

        if inserted_id is None:
            log.info(
                "trade_fill_dedup_hit",
                extra={
                    "client_order_id": facts.client_order_id,
                    "broker_trade_id": facts.broker_trade_id,
                    "deployment_id": str(facts.deployment_id),
                    "note": "existing row with same broker_trade_id; likely reconciliation replay",
                },
            )
            return False

        log.info(
            "trade_fill_persisted",
            extra={
                "trade_id": str(inserted_id),
                "client_order_id": facts.client_order_id,
                "broker_trade_id": facts.broker_trade_id,
                "deployment_id": str(facts.deployment_id),
                "instrument": facts.instrument,
                "side": facts.side,
                "quantity": str(facts.quantity),
                "price": str(facts.price),
            },
        )
        return True

    async def update_trade_pnl(
        self,
        *,
        closing_order_id: str,
        deployment_id: UUID,
        realized_pnl: Decimal,
    ) -> bool:
        """Set ``pnl`` on the Trade row that closed a position.

        Called from the ``PositionClosed`` handler — that event
        carries ``closing_order_id`` (= ``client_order_id`` on the
        fill) and ``realized_pnl`` for the entire position. We match
        on ``(deployment_id, client_order_id)`` and UPDATE the most
        recent fill for that order. Returns ``True`` when a row was
        updated, ``False`` when no match was found.
        """
        from sqlalchemy import update

        async with self._db() as session, session.begin():
            result = await session.execute(
                update(Trade)
                .where(
                    Trade.deployment_id == deployment_id,
                    Trade.client_order_id == closing_order_id,
                )
                .values(pnl=realized_pnl)
                .returning(Trade.id)
            )
            row_id = result.scalar_one_or_none()

        if row_id is None:
            log.warning(
                "trade_pnl_update_no_match",
                extra={
                    "closing_order_id": closing_order_id,
                    "deployment_id": str(deployment_id),
                    "realized_pnl": str(realized_pnl),
                },
            )
            return False

        log.info(
            "trade_pnl_updated",
            extra={
                "trade_id": str(row_id),
                "closing_order_id": closing_order_id,
                "realized_pnl": str(realized_pnl),
            },
        )
        return True

    async def update_partially_filled(self, client_order_id: str) -> None:
        """Order partially filled — not yet terminal, further fills
        may follow and will flip it to ``filled``."""
        await self._update_status(client_order_id, status=_ORDER_STATUS_PARTIALLY_FILLED)

    async def update_cancelled(self, client_order_id: str, *, reason: str | None = None) -> None:
        """Order cancelled (by the caller or by broker timeout)."""
        await self._update_status(client_order_id, status=_ORDER_STATUS_CANCELLED, reason=reason)

    async def update_rejected(self, client_order_id: str, *, reason: str | None) -> None:
        """Broker rejected the order. The ``reason`` is typically the
        broker's error message (e.g. 'Insufficient buying power')."""
        await self._update_status(client_order_id, status=_ORDER_STATUS_REJECTED, reason=reason)

    async def update_denied(self, client_order_id: str, *, reason: str | None) -> None:
        """Risk engine denied the order before submission. The row
        still carries ``deployment_id`` but ``broker_order_id`` stays
        NULL forever because the order never reached the broker.

        UPDATE-only: this transitions an EXISTING row (one a prior
        ``write_submitted`` inserted). For a PRE-SUBMIT halt block —
        where no ``submitted`` row was ever inserted — use
        :meth:`write_denied`, which UPSERTs the complete row.
        """
        await self._update_status(client_order_id, status=_ORDER_STATUS_DENIED, reason=reason)

    async def write_denied(self, facts: OrderDeniedFacts) -> UUID:
        """Durably record a node-side DENIAL, INSERTing a complete
        ``denied`` row when none exists yet, or flipping the existing
        row to ``denied`` when a ``submitted`` row already does.

        PR 2 T2 audit-completeness fix. A node-side halt block returns
        BEFORE the order reaches Nautilus, so the engine-level audit
        hook never inserts a ``submitted`` row — a bare
        :meth:`update_denied` would UPDATE nothing and the real-money
        denial would go unrecorded (``nautilus.md`` #10 violation).
        This method does an idempotent ``INSERT ... ON CONFLICT
        (client_order_id) DO UPDATE`` so the denial is recorded
        atomically whether or not a row preexists:

        - No prior row (the halt-block case) → INSERT the full
          ``denied`` row from ``facts``.
        - A ``submitted`` row preexists (a denial AFTER a real
          submission) → flip THAT row to ``status='denied'`` + set the
          reason, WITHOUT touching the immutable submit-time columns
          (instrument/side/quantity/…) and WITHOUT duplicating the
          row (the ``client_order_id`` UNIQUE index drives the
          conflict target).
        - A duplicate denial for the same ``client_order_id`` → no
          error, the row simply re-asserts ``denied`` + reason.

        Returns the affected row's primary key. ``broker_order_id``
        is never set on this path (the order never reached the
        broker), and the ON CONFLICT clause does not touch it, so a
        post-acceptance denial preserves any broker id already there.

        Raises:
            ValueError: If neither ``deployment_id`` nor
                ``backtest_id`` is populated (the XOR CHECK constraint
                would reject it anyway — surfaced early with the
                ``client_order_id`` context, mirroring
                :meth:`write_submitted`).
        """
        if (facts.deployment_id is None) == (facts.backtest_id is None):
            raise ValueError(
                "OrderDeniedFacts must set exactly one of "
                "deployment_id / backtest_id (the XOR CHECK constraint "
                "on order_attempt_audits rejects any other shape). "
                f"client_order_id={facts.client_order_id}"
            )

        row_id = uuid4()
        stmt = (
            pg_insert(OrderAttemptAudit)
            .values(
                id=row_id,
                client_order_id=facts.client_order_id,
                deployment_id=facts.deployment_id,
                backtest_id=facts.backtest_id,
                strategy_id=facts.strategy_id,
                strategy_code_hash=facts.strategy_code_hash,
                strategy_git_sha=facts.strategy_git_sha,
                instrument_id=facts.instrument_id,
                side=facts.side,
                quantity=facts.quantity,
                price=facts.price,
                order_type=facts.order_type,
                ts_attempted=facts.ts_attempted,
                status=_ORDER_STATUS_DENIED,
                reason=facts.reason,
                is_live=facts.is_live,
            )
            # On conflict (a ``submitted`` row already exists for this
            # client_order_id), only transition status + reason. The
            # submit-time identity columns and any broker_order_id are
            # left untouched.
            .on_conflict_do_update(
                index_elements=["client_order_id"],
                set_={"status": _ORDER_STATUS_DENIED, "reason": facts.reason},
            )
            .returning(OrderAttemptAudit.id)
        )
        async with self._db() as session, session.begin():
            result = await session.execute(stmt)
            affected_id = result.scalar_one()

        log.info(
            "order_audit_denied_recorded",
            extra={
                "client_order_id": facts.client_order_id,
                "deployment_id": str(facts.deployment_id) if facts.deployment_id else None,
                "instrument_id": facts.instrument_id,
                "reason": facts.reason,
                "inserted_new_row": affected_id == row_id,
            },
        )
        return affected_id

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    async def _update_status(
        self,
        client_order_id: str,
        *,
        status: str,
        broker_order_id: str | None = None,
        reason: str | None = None,
    ) -> bool:
        """Apply one status transition to the row keyed by
        ``client_order_id``.

        Only mutates columns the caller provided — NULL in any
        keyword-only argument means "leave this column as-is". That
        way ``update_filled`` doesn't clobber the ``broker_order_id``
        that ``update_accepted`` wrote earlier in the lifecycle.
        """
        values: dict[str, object] = {"status": status}
        if broker_order_id is not None:
            values["broker_order_id"] = broker_order_id
        if reason is not None:
            values["reason"] = reason

        async with self._db() as session, session.begin():
            result = await session.execute(
                update(OrderAttemptAudit)
                .where(OrderAttemptAudit.client_order_id == client_order_id)
                .values(**values)
                .returning(OrderAttemptAudit.id)
            )
            row_id = result.scalar_one_or_none()

        if row_id is None:
            # No row to update — log loudly but don't raise. The
            # caller (Strategy event handler) can't do anything
            # meaningful with an exception here, and the audit is a
            # best-effort recording path.
            log.error(
                "order_audit_update_missing_row",
                extra={
                    "client_order_id": client_order_id,
                    "status": status,
                },
            )
            return False

        log.info(
            "order_audit_status_updated",
            extra={
                "client_order_id": client_order_id,
                "status": status,
                "broker_order_id": broker_order_id,
            },
        )
        return True


async def lookup_by_client_order_id(
    db: async_sessionmaker[AsyncSession], client_order_id: str
) -> OrderAttemptAudit | None:
    """Read-only helper: fetch an audit row by its correlation key.

    Used by tests and by operator debug tooling. Returns ``None`` if
    no row is found rather than raising so callers can distinguish
    "never written" from "deleted".
    """
    async with db() as session:
        result = await session.execute(
            select(OrderAttemptAudit).where(OrderAttemptAudit.client_order_id == client_order_id)
        )
        return result.scalar_one_or_none()


def utc_now() -> datetime:
    """Stable ``datetime.now(UTC)`` callable for test monkey-patching."""
    return datetime.now(UTC)
